name: deploy

on:
  push:
    branches:
      - main
      - 'SeferMirza:issue/**'
jobs:
  set-environment:
    name: Set Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.check-and-set.outputs.environment }}
    steps:
      - name: Check and Set
        id: check-and-set
        run: |
          if [ "${{ github.repository_owner }}" == "gcbrains" ] ;
            then
              echo "environment=production" >> $GITHUB_OUTPUT
          else
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi
  generate:
    name: Generate
    runs-on: ubuntu-latest
    needs: set-environment
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: |
          cd .theme
          npm install
          npm run generate:${{ needs.set-environment.outputs.environment }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: .theme/.output/public
          if-no-files-found: error
  publish:
    needs: generate
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: deploy
          submodules: recursive
      - name: Remove Old Files
        run: |
          git rm -rf .
          git clean -fxd
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: docs
      - name: Commit & Push
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@users.noreply.github.com'
          git add -A
          git commit -m 'deploy to github pages'
          git push -f